name: PZPAudio
favicon: null
layout_spectrum: 0.48034
typography_spectrum: 0.62755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313131'
    - '#5a5a5a'
    - '#dda7fa'
    - '#ffffff'
    - '#65bbe9'
  brandStrength: 0.5077577263582498
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
