name: PZPAudio
favicon: null
layout_spectrum: 0.75
typography_spectrum: 0.62755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1a99fc'
    - '#1169ad'
    - '#06263f'
    - '#0b426e'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
